---
title: "Experiment 1 Qual Analysis"
author: "Cindy Xiong"
output:
  html_document:
    code_folding: hide
    fig_height: 6
    fig_width: 8
    highlight: pygments
    theme: yeti
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
always_allow_html: yes
---
```{r hide-messages}
library(knitr)
opts_chunk$set(warning = FALSE, message = FALSE, comment = FALSE)
```

Uploading appropriate libraries

```{r library, warnings=FALSE, warning=FALSE, message=FALSE}
# include packages
library(tidyr)
library(dplyr)
library(heplots)
library(MANOVA.RM)
library(multcomp)
library(lme4)
library(stringr)
library(ggplot2)
library(car)
library(sjstats)
# package for Chi-Square
library(MASS)    
```

Load data

```{r load-data}
redraw <- read.csv("exp1_redraw_clean.csv")
```

```{r}
# include only the 24 participants with correct counterbalancing
redraw <- redraw %>% filter(p == "s1" | p == "s2" | p == "s4" | p == "s5" |p == "s7" | p == "s8" |
                    p == "s9" | p == "s10" | p == "s11"  | p == "s12" | p == "s14" | p == "s15" |  p == "s16" |
                     p == "s17" | p == "s18" | p == "s19" | p == "s21" | p == "s28" | p == "s29" | p == "s30" |
                     p == "s31" | p == "s32" |  p == "s33" | p == "s34" )
```

```{r}
redraw %>% 
  group_by(design, topic) %>%
  summarise(n = n(), n = n)
```

Visualize 

```{r}
redraw_all %>% 
  group_by(design) %>%
  mutate(percent = n/sum(n)) %>%
  mutate(se = sqrt((n/sum(n))*(1-n/sum(n))/n)) %>% 
  filter(score == 1) %>%
  ggplot(aes(x = 1, y = percent, ymin = percent - se, ymax = percent + se)) +
  geom_bar(stat = "identity", width = 0.5, position = position_dodge(width = 0.03)) +
  geom_errorbar(width = 0.03,
                position = position_dodge(0.2)) + 
  ylim(0, 1) + 
  xlim(0.75, 1.25) +
  facet_wrap(~design) + 
  coord_flip() +
  theme_void() + 
  ggsave("redraw_all.pdf", width = 12, height = 3)
```

```{r}
redraw %>%
  group_by(design, topic, score) %>%
    summarise(n = n(), n = n) %>% 
  group_by(design, topic) %>%
  mutate(percent = n/sum(n)) %>%
  filter(score == 1) %>%
  ggplot(aes(x = topic, y = percent)) +
  geom_bar(stat = "identity", width = 0.6, position = position_dodge(width = 0.2)) +
  ylim(0, 1) + 
  coord_flip() +
  facet_grid(cols = vars(design)) + 
  theme_minimal() +
  ggsave("redraw_topic.pdf", width = 12, height = 7)
```





Models

```{r relevance-score}
model <- lmer(score ~ design*topic + (1|p), data = redraw)

Anova(model)
anova_stats(model)

summary(glht(model , linfct=mcp(design = "Tukey")))
summary(glht(model , linfct=mcp(topic = "Tukey")))
```



